# Generated by Django 3.1.12 on 2021-09-26 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20210925_2004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavorRecipes',
            new_name='FavorRecipe',
        ),
        migrations.AddConstraint(
            model_name='favorrecipe',
            constraint=models.UniqueConstraint(fields=('author', 'recipes'), name='favorite_author_unique_recipes'),
        ),
        migrations.AddConstraint(
            model_name='recipecomponent',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipe'), name='recipe_unique_component'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.UniqueConstraint(fields=('author', 'recipes'), name='shopping_author_recipes_unique'),
        ),
    ]
